### ISSUE TITLE
uhhhhhhh idk [Not Loading Correctly]

### ISSUE THREAD

**Issue by Fooshcookie** [prodzpod/ProdzpodSpikestripContent#1]
Not working. Probably a mod conflict. I can't say much beside providing a log. 

So, log.

[LogOutput.log](https://github.com/user-attachments/files/17108095/LogOutput.log)

**Comment by Fooshcookie** [comment]
[LogOutput.log](https://github.com/user-attachments/files/17108188/LogOutput.log) Real and true. (Part 2 - New Log)

**Comment by Fooshcookie** [comment]
[LogOutput.log](https://github.com/user-attachments/files/17108277/LogOutput.log)
Log Three - I Climbed A Tree

**Comment by prodzpod** [comment]
we found the issue, wait for like 12 hours until we get approved for new version upload
